### ISSUE TITLE
Commands registered the same as BuilderTools

### ISSUE THREAD

**Issue by KadTheHunter** [Muqsit/WorldStyler#26]
Commands such as `//copy`  and `//set` are registered/named just like BuilderTools and MagicWE2. After figuring this out I've removed BT from my server (your plugin is much better in comparison), but for others who wish to have both, this could be an issue, as they could set the positions using //1 and //2 from the other plugins, and then attempt to use //copy (like I did), and it will use WorldStylers //copy, and thus give an error saying you haven't selected the vertices, because you selected them with another plugin.

**Comment by SalmonDE** [comment]
At face value this issue seems to be not a real problem. For collisions like these the fallback prefix is used:
[https://forums.pmmp.io/threads/enforcement-of-rule-c2a-fallback-prefix.6995/](https://forums.pmmp.io/threads/enforcement-of-rule-c2a-fallback-prefix.6995/)
