### ISSUE TITLE
Doesnt place certain blocks.

### ISSUE THREAD

**Issue by ZandercraftGames** [Muqsit/WorldStyler#9]
When filling with certain blocks like invisible bedrock it required the id to work or else it treats the command as if you had done //set 0 and with stained glass even if you use the ID it treats it like a //set 0.

**Comment by Muqsit** [comment]
Can you send the command you typed in?

**Comment by ZandercraftGames** [comment]
Quick edit... It places stained glass as invisible bedrock.

**Comment by ZandercraftGames** [comment]
for invisible bedrock I do `//set invisible_bedrock`
for white stained glass I do `//set stained_glass`
or `//set 95`

**Comment by ZandercraftGames** [comment]
oh... apparently invisible bedrock and white stained glass share the same ID... nice one mojang! :-1:

**Comment by Ifera** [comment]
No they don't. On PC Item ID 95 equals white stained glass. On PE Item ID 95 equals invisible block

**Comment by ZandercraftGames** [comment]
![screenshot from 2018-08-13 13-32-03](https://user-images.githubusercontent.com/28664144/44047753-55901e84-9efd-11e8-91ec-64db5c0ac029.png)

**Comment by ZandercraftGames** [comment]
But that still doesnt explain stained_glass and invisible_bedrock not working.

**Comment by Ifera** [comment]
it should be //set white_stained_glass

**Comment by Ifera** [comment]
![expla](https://user-images.githubusercontent.com/32965703/44048288-5b85a0be-9f4a-11e8-969c-16a337951aa6.PNG)

**Comment by Ifera** [comment]
@ZandercraftGames that explains all

**Comment by Ifera** [comment]
@Muqsit this can be closed now
Also @ZandercraftGames its `invisiblebedrock` and not `invisible_bedrock`

**Comment by Muqsit** [comment]
P.S. Check the BlockIds.php and ItemIds.php files from the pocketmine source code for the correct naming.
